services:
  server:
    container_name: server
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - app-network

  client:
    container_name: client
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
